### ISSUE TITLE
Location not correct

### ISSUE THREAD

**Issue by skapytek** [jsdelivr/globalping-hwprobe#14]
[2023-02-03 17:46:58] [INFO] [688] [api:connect] connected from (Laakirchen, AT, EU) (lat: 47.9819 long: 13.8217)

Its not the correct location.
Its the nearest datacenter from my ISP (im using the hardware-probe from my home location)
Is there any way to change it to my exact home town?

**Comment by jimaek** [comment]
Not at the moment unfortunately, but please report this issue in our main GeoIP task. We will use that data to improve our detection logic. https://github.com/jsdelivr/globalping/issues/268
