### ISSUE TITLE
root-servers.net

### ISSUE THREAD

**Issue by skapytek** [jsdelivr/globalping-hwprobe#17]
Could not chdir to home directory /home/logs: No such file or directory
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
Checking for the latest version
Current version 0.14.0
Latest version 0.20.0
Start self-update process
Self-update finished
[2023-04-12 22:55:13] [INFO] [695] [general] Start probe version 0.20.0 in a production mode
[2023-04-12 22:55:14] [DEBUG] [695] [general] connection to API established
[2023-04-12 22:55:14] [INFO] [695] [api:connect] connected from (Laakirchen, AT, EU) (lat: 47.9849 long: 13.8183)
[2023-04-12 23:05:17] [WARN] [695] [status-manager] ping test result don't match criterias:
{
  status: 'finished',
  resolvedAddress: '199.7.83.42',
  resolvedHostname: 'l.root-servers.net',
  timings: [
    { ttl: 56, rtt: 37.3 },
    { ttl: 56, rtt: 30.9 },
    { ttl: 56, rtt: 31.1 },
    { ttl: 56, rtt: 30.9 },
    { ttl: 56, rtt: 30.1 },
    { ttl: 56, rtt: 34.5 }
  ],
  stats: {
    min: 30.106,
    avg: 32.471,
    max: 37.342,
    total: 7,
    loss: 14.2857,
    rcv: 6,
    drop: 1
  },
  rawOutput: 'PING l.root-servers.net (199.7.83.42) 56(84) bytes of data.\n' +
    '64 bytes from l.root-servers.net (199.7.83.42): icmp_seq=1 ttl=56 time=37.3 ms\n' +
    '64 bytes from l.root-servers.net (199.7.83.42): icmp_seq=3 ttl=56 time=30.9 ms\n' +
    '64 bytes from l.root-servers.net (199.7.83.42): icmp_seq=4 ttl=56 time=31.1 ms\n' +
    '64 bytes from l.root-servers.net (199.7.83.42): icmp_seq=5 ttl=56 time=30.9 ms\n' +
    '64 bytes from l.root-servers.net (199.7.83.42): icmp_seq=6 ttl=56 time=30.1 ms\n' +
    '64 bytes from l.root-servers.net (199.7.83.42): icmp_seq=7 ttl=56 time=34.5 ms\n' +
    '\n' +
    '--- l.root-servers.net ping statistics ---\n' +
    '7 packets transmitted, 6 received, 14.2857% packet loss, time 1206ms\n' +
    'rtt min/avg/max/mdev = 30.106/32.471/37.342/2.597 ms'
}
[2023-04-12 23:05:17] [WARN] [695] [status-manager] ping test result don't match criterias:
{
  status: 'finished',
  resolvedAddress: '193.0.14.129',
  resolvedHostname: 'k.root-servers.net',
  timings: [
    { ttl: 57, rtt: 18.7 },
    { ttl: 57, rtt: 14.2 },
    { ttl: 57, rtt: 14.4 },
    { ttl: 57, rtt: 14.9 },
    { ttl: 57, rtt: 15.1 },
    { ttl: 57, rtt: 15 }
  ],
  stats: {
    min: 14.189,
    avg: 15.381,
    max: 18.725,
    total: 7,
    loss: 14.2857,
    rcv: 6,
    drop: 1
  },
  rawOutput: 'PING k.root-servers.net (193.0.14.129) 56(84) bytes of data.\n' +
    '64 bytes from k.root-servers.net (193.0.14.129): icmp_seq=1 ttl=57 time=18.7 ms\n' +
    '64 bytes from k.root-servers.net (193.0.14.129): icmp_seq=3 ttl=57 time=14.2 ms\n' +
    '64 bytes from k.root-servers.net (193.0.14.129): icmp_seq=4 ttl=57 time=14.4 ms\n' +
    '64 bytes from k.root-servers.net (193.0.14.129): icmp_seq=5 ttl=57 time=14.9 ms\n' +
    '64 bytes from k.root-servers.net (193.0.14.129): icmp_seq=6 ttl=57 time=15.1 ms\n' +
    '64 bytes from k.root-servers.net (193.0.14.129): icmp_seq=7 ttl=57 time=15.0 ms\n' +
    '\n' +
    '--- k.root-servers.net ping statistics ---\n' +
    '7 packets transmitted, 6 received, 14.2857% packet loss, time 1206ms\n' +
    'rtt min/avg/max/mdev = 14.189/15.381/18.725/1.531 ms'
}
[2023-04-13 01:05:37] [WARN] [695] [status-manager] ping test result don't match criterias:
{
  status: 'finished',
  resolvedAddress: '193.0.14.129',
  resolvedHostname: 'k.root-servers.net',
  timings: [
    { ttl: 57, rtt: 21.5 },
    { ttl: 57, rtt: 12.8 },
    { ttl: 57, rtt: 12.7 },
    { ttl: 57, rtt: 12.6 },
    { ttl: 57, rtt: 12.8 },
    { ttl: 57, rtt: 12.9 }
  ],
  stats: {
    min: 12.609,
    avg: 14.196,
    max: 21.462,
    total: 7,
    loss: 14.2857,
    rcv: 6,
    drop: 1
  },
  rawOutput: 'PING k.root-servers.net (193.0.14.129) 56(84) bytes of data.\n' +
    '64 bytes from k.root-servers.net (193.0.14.129): icmp_seq=1 ttl=57 time=21.5 ms\n' +
    '64 bytes from k.root-servers.net (193.0.14.129): icmp_seq=3 ttl=57 time=12.8 ms\n' +
    '64 bytes from k.root-servers.net (193.0.14.129): icmp_seq=4 ttl=57 time=12.7 ms\n' +
    '64 bytes from k.root-servers.net (193.0.14.129): icmp_seq=5 ttl=57 time=12.6 ms\n' +
    '64 bytes from k.root-servers.net (193.0.14.129): icmp_seq=6 ttl=57 time=12.8 ms\n' +
    '64 bytes from k.root-servers.net (193.0.14.129): icmp_seq=7 ttl=57 time=12.9 ms\n' +
    '\n' +
    '--- k.root-servers.net ping statistics ---\n' +
    '7 packets transmitted, 6 received, 14.2857% packet loss, time 1207ms\n' +
    'rtt min/avg/max/mdev = 12.609/14.196/21.462/3.250 ms'
}
[2023-04-13 02:45:56] [WARN] [695] [status-manager] ping test result don't match criterias:
{
  status: 'finished',
  resolvedAddress: '192.58.128.30',
  resolvedHostname: 'j.root-servers.net',
  timings: [
    { ttl: 250, rtt: 15.2 },
    { ttl: 250, rtt: 12.9 },
    { ttl: 250, rtt: 12.4 },
    { ttl: 250, rtt: 12.6 },
    { ttl: 250, rtt: 13.6 },
    { ttl: 250, rtt: 12.4 }
  ],
  stats: {
    min: 12.428,
    avg: 13.2,
    max: 15.184,
    total: 7,
    loss: 14.2857,
    rcv: 6,
    drop: 1
  },
  rawOutput: 'PING j.root-servers.net (192.58.128.30) 56(84) bytes of data.\n' +
    '64 bytes from j.root-servers.net (192.58.128.30): icmp_seq=1 ttl=250 time=15.2 ms\n' +
    '64 bytes from j.root-servers.net (192.58.128.30): icmp_seq=3 ttl=250 time=12.9 ms\n' +
    '64 bytes from j.root-servers.net (192.58.128.30): icmp_seq=4 ttl=250 time=12.4 ms\n' +
    '64 bytes from j.root-servers.net (192.58.128.30): icmp_seq=5 ttl=250 time=12.6 ms\n' +
    '64 bytes from j.root-servers.net (192.58.128.30): icmp_seq=6 ttl=250 time=13.6 ms\n' +
    '64 bytes from j.root-servers.net (192.58.128.30): icmp_seq=7 ttl=250 time=12.4 ms\n' +
    '\n' +
    '--- j.root-servers.net ping statistics ---\n' +
    '7 packets transmitted, 6 received, 14.2857% packet loss, time 1209ms\n' +
    'rtt min/avg/max/mdev = 12.428/13.200/15.184/0.970 ms'
}
[2023-04-13 05:06:15] [WARN] [695] [status-manager] ping test result don't match criterias:
{
  status: 'finished',
  resolvedAddress: '193.0.14.129',
  resolvedHostname: 'k.root-servers.net',
  timings: [
    { ttl: 57, rtt: 23.6 },
    { ttl: 57, rtt: 12.9 },
    { ttl: 57, rtt: 12.6 },
    { ttl: 57, rtt: 12.8 },
    { ttl: 57, rtt: 12.8 },
    { ttl: 57, rtt: 12.5 }
  ],
  stats: {
    min: 12.542,
    avg: 14.534,
    max: 23.597,
    total: 7,
    loss: 14.2857,
    rcv: 6,
    drop: 1
  },
  rawOutput: 'PING k.root-servers.net (193.0.14.129) 56(84) bytes of data.\n' +
    '64 bytes from k.root-servers.net (193.0.14.129): icmp_seq=1 ttl=57 time=23.6 ms\n' +
    '64 bytes from k.root-servers.net (193.0.14.129): icmp_seq=3 ttl=57 time=12.9 ms\n' +
    '64 bytes from k.root-servers.net (193.0.14.129): icmp_seq=4 ttl=57 time=12.6 ms\n' +
    '64 bytes from k.root-servers.net (193.0.14.129): icmp_seq=5 ttl=57 time=12.8 ms\n' +
    '64 bytes from k.root-servers.net (193.0.14.129): icmp_seq=6 ttl=57 time=12.8 ms\n' +
    '64 bytes from k.root-servers.net (193.0.14.129): icmp_seq=7 ttl=57 time=12.5 ms\n' +
    '\n' +
    '--- k.root-servers.net ping statistics ---\n' +
    '7 packets transmitted, 6 received, 14.2857% packet loss, time 1210ms\n' +
    'rtt min/avg/max/mdev = 12.542/14.534/23.597/4.055 ms'
}
[2023-04-13 07:06:35] [WARN] [695] [status-manager] ping test result don't match criterias:
{
  status: 'finished',
  resolvedAddress: '192.58.128.30',
  resolvedHostname: 'j.root-servers.net',
  timings: [
    { ttl: 250, rtt: 22.7 },
    { ttl: 250, rtt: 12.1 },
    { ttl: 250, rtt: 12.1 },
    { ttl: 250, rtt: 13.1 },
    { ttl: 250, rtt: 12.7 },
    { ttl: 250, rtt: 16.2 }
  ],
  stats: {
    min: 12.078,
    avg: 14.81,
    max: 22.731,
    total: 7,
    loss: 14.2857,
    rcv: 6,
    drop: 1
  },
  rawOutput: 'PING j.root-servers.net (192.58.128.30) 56(84) bytes of data.\n' +
    '64 bytes from j.root-servers.net (192.58.128.30): icmp_seq=1 ttl=250 time=22.7 ms\n' +
    '64 bytes from j.root-servers.net (192.58.128.30): icmp_seq=3 ttl=250 time=12.1 ms\n' +
    '64 bytes from j.root-servers.net (192.58.128.30): icmp_seq=4 ttl=250 time=12.1 ms\n' +
    '64 bytes from j.root-servers.net (192.58.128.30): icmp_seq=5 ttl=250 time=13.1 ms\n' +
    '64 bytes from j.root-servers.net (192.58.128.30): icmp_seq=6 ttl=250 time=12.7 ms\n' +
    '64 bytes from j.root-servers.net (192.58.128.30): icmp_seq=7 ttl=250 time=16.2 ms\n' +
    '\n' +
    '--- j.root-servers.net ping statistics ---\n' +
    '7 packets transmitted, 6 received, 14.2857% packet loss, time 1217ms\n' +
    'rtt min/avg/max/mdev = 12.078/14.810/22.731/3.803 ms'
}
[2023-04-13 10:47:07] [WARN] [695] [status-manager] ping test result don't match criterias:
{
  status: 'finished',
  resolvedAddress: '193.0.14.129',
  resolvedHostname: 'k.root-servers.net',
  timings: [
    { ttl: 57, rtt: 23.4 },
    { ttl: 57, rtt: 13.1 },
    { ttl: 57, rtt: 13.6 },
    { ttl: 57, rtt: 13.5 },
    { ttl: 57, rtt: 12 },
    { ttl: 57, rtt: 13.5 }
  ],
  stats: {
    min: 12.024,
    avg: 14.863,
    max: 23.421,
    total: 7,
    loss: 14.2857,
    rcv: 6,
    drop: 1
  },
  rawOutput: 'PING k.root-servers.net (193.0.14.129) 56(84) bytes of data.\n' +
    '64 bytes from k.root-servers.net (193.0.14.129): icmp_seq=1 ttl=57 time=23.4 ms\n' +
    '64 bytes from k.root-servers.net (193.0.14.129): icmp_seq=3 ttl=57 time=13.1 ms\n' +
    '64 bytes from k.root-servers.net (193.0.14.129): icmp_seq=4 ttl=57 time=13.6 ms\n' +
    '64 bytes from k.root-servers.net (193.0.14.129): icmp_seq=5 ttl=57 time=13.5 ms\n' +
    '64 bytes from k.root-servers.net (193.0.14.129): icmp_seq=6 ttl=57 time=12.0 ms\n' +
    '64 bytes from k.root-servers.net (193.0.14.129): icmp_seq=7 ttl=57 time=13.5 ms\n' +
    '\n' +
    '--- k.root-servers.net ping statistics ---\n' +
    '7 packets transmitted, 6 received, 14.2857% packet loss, time 1207ms\n' +
    'rtt min/avg/max/mdev = 12.024/14.863/23.421/3.864 ms'
}
[2023-04-13 11:17:12] [WARN] [695] [status-manager] ping test result don't match criterias:
{
  status: 'finished',
  resolvedAddress: '192.58.128.30',
  resolvedHostname: 'j.root-servers.net',
  timings: [
    { ttl: 250, rtt: 21.5 },
    { ttl: 250, rtt: 16.7 },
    { ttl: 250, rtt: 18.5 },
    { ttl: 250, rtt: 17.2 },
    { ttl: 250, rtt: 16.9 },
    { ttl: 250, rtt: 12.1 }
  ],
  stats: {
    min: 12.142,
    avg: 17.157,
    max: 21.466,
    total: 7,
    loss: 14.2857,
    rcv: 6,
    drop: 1
  },
  rawOutput: 'PING j.root-servers.net (192.58.128.30) 56(84) bytes of data.\n' +
    '64 bytes from j.root-servers.net (192.58.128.30): icmp_seq=1 ttl=250 time=21.5 ms\n' +
    '64 bytes from j.root-servers.net (192.58.128.30): icmp_seq=3 ttl=250 time=16.7 ms\n' +
    '64 bytes from j.root-servers.net (192.58.128.30): icmp_seq=4 ttl=250 time=18.5 ms\n' +
    '64 bytes from j.root-servers.net (192.58.128.30): icmp_seq=5 ttl=250 time=17.2 ms\n' +
    '64 bytes from j.root-servers.net (192.58.128.30): icmp_seq=6 ttl=250 time=16.9 ms\n' +
    '64 bytes from j.root-servers.net (192.58.128.30): icmp_seq=7 ttl=250 time=12.1 ms\n' +
    '\n' +
    '--- j.root-servers.net ping statistics ---\n' +
    '7 packets transmitted, 6 received, 14.2857% packet loss, time 1213ms\n' +
    'rtt min/avg/max/mdev = 12.142/17.157/21.466/2.763 ms'
}
[2023-04-13 11:47:16] [WARN] [695] [status-manager] ping test result don't match criterias:
{
  status: 'finished',
  resolvedAddress: '192.58.128.30',
  resolvedHostname: 'j.root-servers.net',
  timings: [
    { ttl: 250, rtt: 16.9 },
    { ttl: 250, rtt: 15.7 },
    { ttl: 250, rtt: 15 },
    { ttl: 250, rtt: 12.8 },
    { ttl: 250, rtt: 13.6 },
    { ttl: 250, rtt: 12.8 }
  ],
  stats: {
    min: 12.75,
    avg: 14.46,
    max: 16.874,
    total: 7,
    loss: 14.2857,
    rcv: 6,
    drop: 1
  },
  rawOutput: 'PING j.root-servers.net (192.58.128.30) 56(84) bytes of data.\n' +
    '64 bytes from j.root-servers.net (192.58.128.30): icmp_seq=1 ttl=250 time=16.9 ms\n' +
    '64 bytes from j.root-servers.net (192.58.128.30): icmp_seq=3 ttl=250 time=15.7 ms\n' +
    '64 bytes from j.root-servers.net (192.58.128.30): icmp_seq=4 ttl=250 time=15.0 ms\n' +
    '64 bytes from j.root-servers.net (192.58.128.30): icmp_seq=5 ttl=250 time=12.8 ms\n' +
    '64 bytes from j.root-servers.net (192.58.128.30): icmp_seq=6 ttl=250 time=13.6 ms\n' +
    '64 bytes from j.root-servers.net (192.58.128.30): icmp_seq=7 ttl=250 time=12.8 ms\n' +
    '\n' +
    '--- j.root-servers.net ping statistics ---\n' +
    '7 packets transmitted, 6 received, 14.2857% packet loss, time 1219ms\n' +
    'rtt min/avg/max/mdev = 12.750/14.460/16.874/1.528 ms'
}
[2023-04-13 14:37:42] [WARN] [695] [status-manager] ping test result don't match criterias:
{
  status: 'finished',
  resolvedAddress: '199.7.83.42',
  resolvedHostname: 'l.root-servers.net',
  timings: [
    { ttl: 56, rtt: 34.2 },
    { ttl: 56, rtt: 33.8 },
    { ttl: 56, rtt: 29.2 },
    { ttl: 56, rtt: 30.1 },
    { ttl: 56, rtt: 29.1 },
    { ttl: 56, rtt: 32.6 }
  ],
  stats: {
    min: 29.116,
    avg: 31.509,
    max: 34.218,
    total: 7,
    loss: 14.2857,
    rcv: 6,
    drop: 1
  },
  rawOutput: 'PING l.root-servers.net (199.7.83.42) 56(84) bytes of data.\n' +
    '64 bytes from l.root-servers.net (199.7.83.42): icmp_seq=1 ttl=56 time=34.2 ms\n' +
    '64 bytes from l.root-servers.net (199.7.83.42): icmp_seq=3 ttl=56 time=33.8 ms\n' +
    '64 bytes from l.root-servers.net (199.7.83.42): icmp_seq=4 ttl=56 time=29.2 ms\n' +
    '64 bytes from l.root-servers.net (199.7.83.42): icmp_seq=5 ttl=56 time=30.1 ms\n' +
    '64 bytes from l.root-servers.net (199.7.83.42): icmp_seq=6 ttl=56 time=29.1 ms\n' +
    '64 bytes from l.root-servers.net (199.7.83.42): icmp_seq=7 ttl=56 time=32.6 ms\n' +
    '\n' +
    '--- l.root-servers.net ping statistics ---\n' +
    '7 packets transmitted, 6 received, 14.2857% packet loss, time 1213ms\n' +
    'rtt min/avg/max/mdev = 29.116/31.509/34.218/2.114 ms'
}
[2023-04-13 15:07:46] [WARN] [695] [status-manager] ping test result don't match criterias:
{
  status: 'finished',
  resolvedAddress: '199.7.83.42',
  resolvedHostname: 'l.root-servers.net',
  timings: [
    { ttl: 56, rtt: 35.7 },
    { ttl: 56, rtt: 29.2 },
    { ttl: 56, rtt: 32.2 },
    { ttl: 56, rtt: 28.9 },
    { ttl: 56, rtt: 29.1 },
    { ttl: 56, rtt: 30 }
  ],
  stats: {
    min: 28.869,
    avg: 30.847,
    max: 35.724,
    total: 7,
    loss: 14.2857,
    rcv: 6,
    drop: 1
  },
  rawOutput: 'PING l.root-servers.net (199.7.83.42) 56(84) bytes of data.\n' +
    '64 bytes from l.root-servers.net (199.7.83.42): icmp_seq=1 ttl=56 time=35.7 ms\n' +
    '64 bytes from l.root-servers.net (199.7.83.42): icmp_seq=3 ttl=56 time=29.2 ms\n' +
    '64 bytes from l.root-servers.net (199.7.83.42): icmp_seq=4 ttl=56 time=32.2 ms\n' +
    '64 bytes from l.root-servers.net (199.7.83.42): icmp_seq=5 ttl=56 time=28.9 ms\n' +
    '64 bytes from l.root-servers.net (199.7.83.42): icmp_seq=6 ttl=56 time=29.1 ms\n' +
    '64 bytes from l.root-servers.net (199.7.83.42): icmp_seq=7 ttl=56 time=30.0 ms\n' +
    '\n' +
    '--- l.root-servers.net ping statistics ---\n' +
    '7 packets transmitted, 6 received, 14.2857% packet loss, time 1217ms\n' +
    'rtt min/avg/max/mdev = 28.869/30.847/35.724/2.445 ms'
}
[2023-04-13 16:38:00] [WARN] [695] [status-manager] ping test result don't match criterias:
{
  status: 'finished',
  resolvedAddress: '193.0.14.129',
  resolvedHostname: 'k.root-servers.net',
  timings: [
    { ttl: 57, rtt: 22.5 },
    { ttl: 57, rtt: 13.5 },
    { ttl: 57, rtt: 13 },
    { ttl: 57, rtt: 12.3 },
    { ttl: 57, rtt: 17 },
    { ttl: 57, rtt: 17.1 }
  ],
  stats: {
    min: 12.256,
    avg: 15.876,
    max: 22.486,
    total: 7,
    loss: 14.2857,
    rcv: 6,
    drop: 1
  },
  rawOutput: 'PING k.root-servers.net (193.0.14.129) 56(84) bytes of data.\n' +
    '64 bytes from k.root-servers.net (193.0.14.129): icmp_seq=1 ttl=57 time=22.5 ms\n' +
    '64 bytes from k.root-servers.net (193.0.14.129): icmp_seq=3 ttl=57 time=13.5 ms\n' +
    '64 bytes from k.root-servers.net (193.0.14.129): icmp_seq=4 ttl=57 time=13.0 ms\n' +
    '64 bytes from k.root-servers.net (193.0.14.129): icmp_seq=5 ttl=57 time=12.3 ms\n' +
    '64 bytes from k.root-servers.net (193.0.14.129): icmp_seq=6 ttl=57 time=17.0 ms\n' +
    '64 bytes from k.root-servers.net (193.0.14.129): icmp_seq=7 ttl=57 time=17.1 ms\n' +
    '\n' +
    '--- k.root-servers.net ping statistics ---\n' +
    '7 packets transmitted, 6 received, 14.2857% packet loss, time 1209ms\n' +
    'rtt min/avg/max/mdev = 12.256/15.876/22.486/3.503 ms'
}

**Comment by jimaek** [comment]
Hey, this is normal. It's a network quality control test and shows the failed tests. If more than 1 endpoint has package loss then we temporarily remove the probe from the network until all tests pass again
