### ISSUE TITLE
how to check if hw-probe is working

### ISSUE THREAD

**Issue by skapytek** [jsdelivr/globalping-hwprobe#19]
Hi,
im using the hardware probe from my fiber internet at my home.
How can i check if my device is connected to the api and resolving requests?
I cant find any ID or something similair to check it on the web api site.

**Comment by jimaek** [comment]
Hey, the instructions that came with the device explain how to connect to the probe to check the logs. The other option is to find your ASN, ISP and City combo in the list of probes https://api.globalping.io/v1/probes

**Comment by skapytek** [comment]
City is not accurate it shows the next pop not directly my home city

**Comment by jimaek** [comment]
Please report geo issues here https://github.com/jsdelivr/globalping/issues/268
