### ISSUE TITLE
Probe not visible on the webapp 

### ISSUE THREAD

**Issue by Albonycal** [jsdelivr/globalping-hwprobe#21]
Error logs: https://paste.debian.net/1282752/

**Comment by jimaek** [comment]
Can you try running these commands on some linux machine a few times and tell me if they fail or not?

```
ping -4 -c 6 -i 0.2 -w 15 k.root-servers.net
ping -4 -c 6 -i 0.2 -w 15 j.root-servers.net
ping -4 -c 6 -i 0.2 -w 15 l.root-servers.net
```

Additionally you can try some other root servers from here https://root-servers.org/ and tell me if some other is more stable for you

**Comment by Albonycal** [comment]
![image](https://github.com/jsdelivr/globalping-hwprobe/assets/67057319/653779db-5878-4ede-9151-8f80de299043)
![image](https://github.com/jsdelivr/globalping-hwprobe/assets/67057319/fd099987-d47d-4ced-bf0f-f13ec54412ca)
![image](https://github.com/jsdelivr/globalping-hwprobe/assets/67057319/9da27af8-b38f-46ab-948b-f229fa478443)
The l root server is dropping packets

**Comment by jimaek** [comment]
In your logs all of them seem to be doing it, so you need to run these commands a few times to be sure.

Also try this and let me know if it improves things or not:

```
ping -4 -c 6 -i 0.3 -w 15 l.root-servers.net
```

**Comment by Albonycal** [comment]
> ping -4 -c 6 -i 0.3 -w 15 l.root-servers.net
Still dropping packets, other ones are not (tested multiple times)

**Comment by Albonycal** [comment]
> In your logs all of them seem to be doing it, 

No they aren't, only `l` rootserver is dropping packets.

a root server is fine, no packetloss

**Comment by jimaek** [comment]
Please send the latest logs from your probe

**Comment by Albonycal** [comment]
https://paste.debian.net/1282818/

**Comment by jimaek** [comment]
I pushed another update, check if your probe now passes the test

**Comment by Albonycal** [comment]
still fails

**Comment by jimaek** [comment]
So far it seems that your internet is indeed unstable. I even included an endpoint by an Indian provider.

The only other potential problem I see is the "-i 0.2 " parameter. So please run many pings over the period of an hour to the failing endpoints in your logs using different values of that parameter to compare if there is a difference. e.g. 0.2, 0.3, 0.4, 0.5

**Comment by Albonycal** [comment]
I don't think my network is unstable.

**Comment by Albonycal** [comment]
Oh wait, I restarted the probe and it downloaded the latest update. And the probe is up now

**Comment by Albonycal** [comment]
Also, I think using geoip database for the location of the probe is not a good idea, there should be a way to hardcode the city. It's not correct. 
![image](https://github.com/jsdelivr/globalping-hwprobe/assets/67057319/0530bce8-b79e-4d85-8cb3-6e82bceae6ae)

**Comment by jimaek** [comment]
> Oh wait, I restarted the probe and it downloaded the latest update. And the probe is up now

Great!

>Also, I think using geoip database for the location of the probe is not a good idea, there should be a way to hardcode the city. It's not correct.

You will get this option once our dashboard goes live. You will also get stats and other features
