### ISSUE TITLE
[2023-08-02 16:17:11] [WARN] [status-manager] Quality control ping test result is unsuccessful: ns1.dns.nl 14.2857% packet loss. Test pass.

### ISSUE THREAD

**Issue by skapytek** [jsdelivr/globalping-hwprobe#23]
hwprobe:
`[2023-08-02 16:17:11] [WARN] [status-manager] Quality control ping test result is unsuccessful: ns1.dns.nl 14.2857% packet loss. Test pass.`
This continues until probe gets disconnected.

from the same network and from different devices (not filtering activated) all ping commands run without any problem:

`Ping-Statistik für 194.0.28.53:
    Pakete: Gesendet = 4, Empfangen = 4, Verloren = 0
    (0% Verlust),
Ca. Zeitangaben in Millisek.:
    Minimum = 35ms, Maximum = 40ms, Mittelwert = 36ms`

So its an hwprobe issue

_Originally posted by @skapytek in https://github.com/jsdelivr/globalping-hwprobe/issues/22#issuecomment-1662848661_

**Comment by jimaek** [comment]
Its not something I can replicate on my probes, they pass all tests 100% of the time. So I dont think its a hardware issue.
If you want you could run a docker container probe on your PC and compare the results.

But its not even a failure, the log you sent is just a warning, you can see at the end that the probe was disconnected ` Test pass.`
