### ISSUE TITLE
Dev build flag

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/globalping-hwprobe#35]
I currently had to build a custom FW to try out a new release of the probe software without releasing it to all users (changed the source for docker image to my repo). I'm wondering if we could have support for this in the official FW instead. E.g., if `JSDELIVR-DEV.UPD` file is present, pull `ghcr.io/jsdelivr/globalping-probe:dev` instead of `ghcr.io/jsdelivr/globalping-probe:latest` - security-wise, this should be fine, since it would still use the official repo, just a different tag.

**Comment by kernelgurumeditation** [comment]
Implemented in the V2 version of the firmware
