### ISSUE TITLE
Using username "logs". Could not chdir to home directory /home/logs: No such file or directory

### ISSUE THREAD

**Issue by joshuakars** [jsdelivr/globalping-hwprobe#41]
After self update my probe, stuck no such file or directory and force close

Shows error

Using username "logs".
Could not chdir to home directory /home/logs: No such file or directory

Try to flash 1.4 on new micro sd card also the same error
![Uploading Screenshot 2024-03-29 210153.png…]()

**Comment by jimaek** [comment]
Hey, thats just a minor warning, it doesn't impact anything and we also removed it from the v2 firmware. You can continue using your probe as usual :)
