### ISSUE TITLE
Probes hostname not resolving

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/globalping-hwprobe#45]
Previously the probe was able to resolve it's name in the LAN to something like globalping-probe-XXXX. But now its just an IP.
Can you please check it works for you @MartinKolarik, maybe its something with my network

https://share.perfstack.net/2024/06/advanced_ip_scanner_2024-06-13_14-58-50.png

**Comment by kernelgurumeditation** [comment]
works for me....

![image](https://github.com/jsdelivr/globalping-hwprobe/assets/19845725/0b8db3ce-d4a2-4c77-8c06-7f7721c71367)

**Comment by MartinKolarik** [comment]
Works for me as well.
